export const apiUrl = 'http://10.1.2.138:8001/';

const zayavki = [
  {
    id: 21,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 12,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 10,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 13,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 15,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 11,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 22,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 20,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 25,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 27,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  },
  {
    id: 29,
    status: "new",
    router_installation: "router",
    tariff: "testtarrif",
    super_tv_installation: "tv",
    description: "lalalalalallaldasdadadsadadsadas",
    hydra_dogovor: "AR/123",
    previous_provider: "aknet",
    first_name: "ara",
    last_name: "Kuliev",
    primary_phone: "99677933944",
    secondary_phone: "99677933977",
    intercom_account: "1234",
    address: "Ул Исанова, дом 123",
    hydra_address: "Кыргызстан Ул Исанова, дом 123",
    hydra_abbon_ls: "175050620",
    passport_front_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    passport_back_image_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    location_url: "https://www.youtube.com/watch?v=rZ4_qZhLmos&list=RDrZ4_qZhLmos&start_radio=1",
    created_at: "2024-03-13T12:56:33.206041Z",
    agent: 57
  }
]

export const getApplications = async () => {
  return zayavki;
};
